"""user: add cat_id

Revision ID: 51811850d1fa
Revises: ebe62e6eba77
Create Date: 2025-01-15 05:59:26.001719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51811850d1fa'
down_revision: Union[str, None] = 'ebe62e6eba77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('cat_id', sa.String(length=50), nullable=True, comment='thread is of cat assistant'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'cat_id')
    # ### end Alembic commands ###
