"""add shares information table

Revision ID: 81dcbc7e2cfc
Revises: a17fef708c9d
Create Date: 2024-07-12 06:33:22.502918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81dcbc7e2cfc'
down_revision: Union[str, None] = 'a17fef708c9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Shares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bot_updated', sa.Integer(), nullable=True, comment='latest bots update time'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Shares_id'), 'Shares', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Shares_id'), table_name='Shares')
    op.drop_table('Shares')
    # ### end Alembic commands ###
