"""add assistant in chat page

Revision ID: a17fef708c9d
Revises: d289719e4bf1
Create Date: 2024-07-07 19:09:23.575418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a17fef708c9d'
down_revision: Union[str, None] = 'd289719e4bf1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Bot', 'vector_store_ids',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='file search file_ids, dict, key: id, val: name}',
               existing_comment='file search file_ids: array',
               existing_nullable=True)
    op.alter_column('Bot', 'code_interpreter_files',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='dict, key: filename, value: file-id',
               existing_comment='code interpreter file_ids: array',
               existing_nullable=True)
    op.alter_column('Bot', 'functions',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='dict, key: name, value: function body',
               existing_comment='function calling: array',
               existing_nullable=True)
    op.add_column('Chat', sa.Column('assistant_id', sa.String(), nullable=True))
    op.add_column('Chat', sa.Column('thread_id', sa.String(), nullable=True))
    op.add_column('Chat', sa.Column('bot_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Chat', 'bot_id')
    op.drop_column('Chat', 'thread_id')
    op.drop_column('Chat', 'assistant_id')
    op.alter_column('Bot', 'functions',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='function calling: array',
               existing_comment='dict, key: name, value: function body',
               existing_nullable=True)
    op.alter_column('Bot', 'code_interpreter_files',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='code interpreter file_ids: array',
               existing_comment='dict, key: filename, value: file-id',
               existing_nullable=True)
    op.alter_column('Bot', 'vector_store_ids',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='file search file_ids: array',
               existing_comment='file search file_ids, dict, key: id, val: name}',
               existing_nullable=True)
    # ### end Alembic commands ###
