"""add timestamp

Revision ID: a3e37810376f
Revises: 8432a66e00f9
Create Date: 2024-03-31 08:48:21.173625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a3e37810376f'
down_revision: Union[str, None] = '8432a66e00f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Chat', sa.Column('model', sa.String(length=50), nullable=True, comment='chat model'))
    op.add_column('Chat', sa.Column('created_at', sa.Integer(), nullable=True))
    op.add_column('Chat', sa.Column('updated_at', sa.Integer(), nullable=True))
    op.alter_column('Chat', 'title',
               existing_type=sa.VARCHAR(length=50),
               comment='this chat title',
               existing_nullable=True)
    op.alter_column('Chat', 'contents',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='chat content of this title',
               existing_nullable=True)
    op.create_index(op.f('ix_Chat_id'), 'Chat', ['id'], unique=False)
    op.create_foreign_key(None, 'Chat', 'User', ['user_id'], ['id'])
    op.add_column('User', sa.Column('created_at', sa.Integer(), nullable=True))
    op.add_column('User', sa.Column('updated_at', sa.Integer(), nullable=True))
    op.alter_column('User', 'name',
               existing_type=sa.VARCHAR(length=50),
               comment='user name',
               existing_nullable=True)
    op.alter_column('User', 'email',
               existing_type=sa.VARCHAR(length=50),
               comment='user email',
               existing_nullable=False)
    op.alter_column('User', 'phone',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               comment='phone number',
               existing_nullable=True)
    op.alter_column('User', 'avatar',
               existing_type=sa.VARCHAR(),
               comment='user avatar',
               existing_nullable=True)
    op.alter_column('User', 'pwd',
               existing_type=sa.VARCHAR(length=200),
               comment='password',
               existing_nullable=False)
    op.alter_column('User', 'active',
               existing_type=sa.BOOLEAN(),
               comment='whether the user is active',
               existing_nullable=True)
    op.create_index(op.f('ix_User_id'), 'User', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_User_id'), table_name='User')
    op.alter_column('User', 'active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='whether the user is active',
               existing_nullable=True)
    op.alter_column('User', 'pwd',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='password',
               existing_nullable=False)
    op.alter_column('User', 'avatar',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='user avatar',
               existing_nullable=True)
    op.alter_column('User', 'phone',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='phone number',
               existing_nullable=True)
    op.alter_column('User', 'email',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='user email',
               existing_nullable=False)
    op.alter_column('User', 'name',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='user name',
               existing_nullable=True)
    op.drop_column('User', 'updated_at')
    op.drop_column('User', 'created_at')
    op.drop_constraint(None, 'Chat', type_='foreignkey')
    op.drop_index(op.f('ix_Chat_id'), table_name='Chat')
    op.alter_column('Chat', 'contents',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='chat content of this title',
               existing_nullable=True)
    op.alter_column('Chat', 'title',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='this chat title',
               existing_nullable=True)
    op.drop_column('Chat', 'updated_at')
    op.drop_column('Chat', 'created_at')
    op.drop_column('Chat', 'model')
    # ### end Alembic commands ###
