"""add Bot table

Revision ID: ac1e0312324f
Revises: 1fda63a49965
Create Date: 2024-04-23 14:30:25.915653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac1e0312324f'
down_revision: Union[str, None] = '1fda63a49965'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Bot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False, comment='bot name'),
    sa.Column('avatar', sa.String(), nullable=True, comment='bot avatar'),
    sa.Column('description', sa.String(), nullable=True, comment='bot detail description'),
    sa.Column('prompts', sa.String(), nullable=False, comment='bot prompts'),
    sa.Column('author_id', sa.Integer(), nullable=True, comment='author id'),
    sa.Column('author_name', sa.String(length=50), nullable=True, comment='author name'),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('public', sa.Boolean(), nullable=True, comment='public or not'),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Bot_id'), 'Bot', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Bot_id'), table_name='Bot')
    op.drop_table('Bot')
    # ### end Alembic commands ###
