"""add mcp table

Revision ID: acbc3a4a798f
Revises: 4e5c4c1addc1
Create Date: 2025-05-14 16:55:41.415617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acbc3a4a798f'
down_revision: Union[str, None] = '4e5c4c1addc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mcp',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('command', sa.String(), nullable=False),
    sa.Column('args', sa.String(), nullable=False),
    sa.Column('custom_environment', sa.JSON(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('owner_name', sa.String(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mcp_id'), 'mcp', ['id'], unique=True)
    op.add_column('Shares', sa.Column('mcp_updated', sa.Integer(), nullable=True, comment='latest mcp server update time'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Shares', 'mcp_updated')
    op.drop_index(op.f('ix_mcp_id'), table_name='mcp')
    op.drop_table('mcp')
    # ### end Alembic commands ###
