"""chat: add internet

Revision ID: b702453e9913
Revises: 51811850d1fa
Create Date: 2025-02-28 06:28:51.547589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b702453e9913'
down_revision: Union[str, None] = '51811850d1fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Chat', sa.Column('internet', sa.Boolean(), nullable=True, comment='enable internet'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Chat', 'internet')
    # ### end Alembic commands ###
