"""add order table

Revision ID: c0e1e961112f
Revises: acbc3a4a798f
Create Date: 2025-06-07 03:49:42.841268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0e1e961112f'
down_revision: Union[str, None] = 'acbc3a4a798f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False, comment='product name'),
    sa.Column('out_trade_no', sa.String(), nullable=False, comment='product trade number'),
    sa.Column('type', sa.String(), nullable=False, comment='trade type(alipay|wxpay)'),
    sa.Column('pid', sa.String(), nullable=False, comment='product id'),
    sa.Column('money', sa.String(), nullable=False, comment='trade money'),
    sa.Column('status', sa.Integer(), nullable=False, comment='trade status(1:success, 0:unpaid)'),
    sa.Column('param', sa.String(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_id'), 'order', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_id'), table_name='order')
    op.drop_table('order')
    # ### end Alembic commands ###
