"""user: add settings

Revision ID: c907f0418370
Revises: b702453e9913
Create Date: 2025-03-01 14:10:28.415472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c907f0418370'
down_revision: Union[str, None] = 'b702453e9913'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('settings', sa.JSON(), nullable=True, comment='user settings'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'settings')
    # ### end Alembic commands ###
