"""add assistant contents

Revision ID: d289719e4bf1
Revises: ac1e0312324f
Create Date: 2024-07-03 07:09:13.115039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd289719e4bf1'
down_revision: Union[str, None] = 'ac1e0312324f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Bot', sa.Column('assistant_id', sa.String(), nullable=True, comment='assistant id'))
    op.add_column('Bot', sa.Column('model', sa.String(), nullable=True, comment='the default model to use'))
    op.add_column('Bot', sa.Column('file_search', sa.Boolean(), nullable=True, comment='enable file search or not'))
    op.add_column('Bot', sa.Column('vector_store_ids', sa.JSON(), nullable=True, comment='file search file_ids: array'))
    op.add_column('Bot', sa.Column('code_interpreter', sa.Boolean(), nullable=True, comment='enable code interpreter or not'))
    op.add_column('Bot', sa.Column('code_interpreter_files', sa.JSON(), nullable=True, comment='code interpreter file_ids: array'))
    op.add_column('Bot', sa.Column('functions', sa.JSON(), nullable=True, comment='function calling: array'))
    op.add_column('Bot', sa.Column('temperature', sa.Float(), nullable=True, comment='sampling temperature, between 0 and 2'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Bot', 'temperature')
    op.drop_column('Bot', 'functions')
    op.drop_column('Bot', 'code_interpreter_files')
    op.drop_column('Bot', 'code_interpreter')
    op.drop_column('Bot', 'vector_store_ids')
    op.drop_column('Bot', 'file_search')
    op.drop_column('Bot', 'model')
    op.drop_column('Bot', 'assistant_id')
    # ### end Alembic commands ###
