"""chat: add artifact

Revision ID: ebe62e6eba77
Revises: 08860f3d8992
Create Date: 2024-08-22 09:28:19.315059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebe62e6eba77'
down_revision: Union[str, None] = '08860f3d8992'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Chat', sa.Column('artifact', sa.Boolean(), nullable=True, comment='enable artifact'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Chat', 'artifact')
    # ### end Alembic commands ###
